<a href="https://colab.research.google.com/github/Tejaswarreddy/MyProjects/blob/main/DataMerging.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [85]:
import pandas as pd
from google.colab import files

In [38]:
content=pd.read_csv("CleanContent.csv",index_col=0)
reactions=pd.read_csv("CleanReactions.csv",index_col=0)
reactiontypes=pd.read_csv("CleanReactiontypes.csv",index_col=0)

In [39]:
reactions.head()

                             Content ID        Type             Datetime
1  97522e57-d9ab-4bd6-97bf-c24d952602d2     disgust  2020-11-07 09:43:50
2  97522e57-d9ab-4bd6-97bf-c24d952602d2     dislike  2021-06-17 12:22:51
3  97522e57-d9ab-4bd6-97bf-c24d952602d2      scared  2021-04-18 05:13:58
4  97522e57-d9ab-4bd6-97bf-c24d952602d2     disgust  2021-01-06 19:13:01
5  97522e57-d9ab-4bd6-97bf-c24d952602d2  interested  2020-08-23 12:25:58

In [16]:
content.head()

                             Content ID   Type        Category
0  97522e57-d9ab-4bd6-97bf-c24d952602d2  photo        Studying
1  9f737e0a-3cdd-4d29-9d24-753f4e3be810  photo  healthy eating
2  230c4e4d-70c3-461d-b42c-ec09396efb3f  photo  healthy eating
3  356fff80-da4d-4785-9f43-bc1261031dc6  photo      technology
4  01ab84dd-6364-4236-abbb-3f237db77180  video            food

In [17]:
reactiontypes.head()

         Type  Score
0       heart     60
1        want     70
2     disgust      0
3        hate      5
4  interested     30

In [40]:
reactions1=pd.merge(reactions,reactiontypes,on='Type')

In [41]:
reactions1.head()

                             Content ID     Type             Datetime  Score
0  97522e57-d9ab-4bd6-97bf-c24d952602d2  disgust  2020-11-07 09:43:50      0
1  97522e57-d9ab-4bd6-97bf-c24d952602d2  disgust  2021-01-06 19:13:01      0
2  97522e57-d9ab-4bd6-97bf-c24d952602d2  disgust  2021-04-09 02:46:20      0
3  9f737e0a-3cdd-4d29-9d24-753f4e3be810  disgust  2021-03-28 21:15:26      0
4  230c4e4d-70c3-461d-b42c-ec09396efb3f  disgust  2020-08-04 05:40:33      0

In [43]:
print(reactions.shape)
print(reactions1.shape)

(24573, 3)
(24573, 4)

In [44]:
content.shape

(801, 3)

In [45]:
reactions2=pd.merge(reactions1,content,on='Content ID')

In [46]:
print(reactions.shape)
print(reactions1.shape)
print(reactions2.shape)

(24573, 3)
(24573, 4)
(20056, 6)

In [52]:
reactions2.head()

,Content ID,Type_x,Datetime,Score,Type_y,Category
0,97522e57-d9ab-4bd6-97bf-c24d952602d2,disgust,2020-11-07 09:43:50,0,photo,Studying
1,97522e57-d9ab-4bd6-97bf-c24d952602d2,disgust,2021-01-06 19:13:01,0,photo,Studying
2,97522e57-d9ab-4bd6-97bf-c24d952602d2,disgust,2021-04-09 02:46:20,0,photo,Studying
3,97522e57-d9ab-4bd6-97bf-c24d952602d2,dislike,2021-06-17 12:22:51,10,photo,Studying
4,97522e57-d9ab-4bd6-97bf-c24d952602d2,dislike,2020-11-09 02:49:59,10,photo,Studying

In [53]:
reactions2=reactions2.rename({'Type_x':'Reaction_type','Type_y':'Content_type'},axis=1)

In [54]:
reactions2.head()

,Content ID,Reaction_type,Datetime,Score,Content_type,Category
0,97522e57-d9ab-4bd6-97bf-c24d952602d2,disgust,2020-11-07 09:43:50,0,photo,Studying
1,97522e57-d9ab-4bd6-97bf-c24d952602d2,disgust,2021-01-06 19:13:01,0,photo,Studying
2,97522e57-d9ab-4bd6-97bf-c24d952602d2,disgust,2021-04-09 02:46:20,0,photo,Studying
3,97522e57-d9ab-4bd6-97bf-c24d952602d2,dislike,2021-06-17 12:22:51,10,photo,Studying
4,97522e57-d9ab-4bd6-97bf-c24d952602d2,dislike,2020-11-09 02:49:59,10,photo,Studying

In [73]:
df=reactions2.groupby(['Category']).agg({'Score':'sum'}).sort_values()

In [74]:
df.head()

          Score
Category
Studying   1341
animals   57418
cooking   54534
culture   52410
dogs      45400

In [78]:
df=df.sort_values(by='Score',ascending=False)

In [79]:
df

                 Score
Category
travel           58946
science          58566
healthy eating   58059
animals          57418
cooking          54534
culture          52410
food             51444
technology       50971
education        49138
tennis           47619
soccer           45776
fitness          45536
dogs             45400
veganism         41725
public speaking  40492
studying         38092
Studying          1341

In [81]:
df1=df[0:5]

In [88]:
df1.to_csv("top_5.csv")

In [87]:
reactions2.to_csv("cleaneddataset.csv")

In [89]:
files.download("top_5.csv")
files.download("cleaneddataset.csv")